name: List of Non standard profiles

on:
  workflow_dispatch:
    inputs:
      action_branch:
        description: The branch of the action to use
        default: main
        
      organization:
        description: The organization to process
        default: internal-test-organization
      remove_flag:
       description: Non standard user removal confirmation 'Yes' or 'No'
       default: 'No' 
jobs:
  orgs:
    name: Analyze Non standard user and sending mail to core team
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.action_branch }}
        
      - name: Analyze organization
        id: analyze_org
        uses: ./
        with:
          token: ${{ secrets.SCB_CHECKOUT_PAT }}
          organization: ${{ github.event.inputs.organization }}
          remove_flag: ${{ github.event.inputs.remove_flag }}
          
      - name: Results of metadata
        run: |
          
          echo "Non- standard User - ${{ steps.analyze_org.outputs.jsonfinallist }}"
          

      - name: Attach Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nonstandardreports
          path: ${{ steps.analyze_org.outputs.jsonfinallist }}
            
      - name: Push report to repository
        run: |
          git config --global user.name '1649901'
          git config --global user.email '1649901@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.MY_PAT }}@github.com/$GITHUB_REPOSITORY
          git checkout "${ GITHUB_REF:11 }"
          git add -f ./lastmonthreport/jsonfinallist.json
          git add .
          git commit -m "Automated report"
          git pull
          git push


      - name: Send mail to core team
        uses: ./
        with:
          # Required mail server address:
          server_address: ${{ secrets.SERVER_ADDRESS }}
          # Required mail server port:
          server_port: ${{ secrets.SERVER_PORT }}
          
          subject: mail to core team
          
          to: pradipta.chatterjee98@gmail.com
          # Required sender full name (address can be skipped):
          from: suripa.saha@sc.com
          
          secure: true
          
          body: Hi Team! The following users with PSID ${{ steps.analyze_org.outputs.jsonfinallist }} are non-standard,
          # Optional carbon copy recipients:
          cc: suripa.saha110@gmail.com
          
          ignore_cert: true
          
          convert_markdown: true
          
        
